server:
  port: 8090
spring:
  data:
    mongodb:
      username: asma
      password: asma
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin